const USER_FACING_OPTION_LABELS: Record<string, string> = {
  Action_Dialogue_Hybrid: "Action with dialogue",
  Active_Collision: "Start in the middle of trouble",
  Antagonistic: "Enemies to lovers",
  Angsty_Melancholic: "Angsty and melancholy",
  Asymmetric: "One leads, one follows",
  "Asymmetric (Bot Dominant)": "Character leads",
  "Asymmetric (User Dominant)": "User leads",
  Atmospheric_Wilderness: "Remote or atmospheric place",
  "Age Gap (Junior)": "Younger age gap",
  "Age Gap (Senior)": "Older age gap",
  Anglophone: "English-speaking",
  "Anglo-Saxon": "English / Anglo-Saxon",
  "Arts_Design": "Arts or design",
  Arts_Entertainment: "Arts or entertainment",
  Biographical_NPC: "Important NPC",
  Betrothed_Promised: "Betrothed or promised",
  Black_African: "Black / African",
  Bracket_Monologue: "Internal monologue",
  Breeding_Claiming: "Breeding or claiming",
  Canon_Divergence: "Canon change",
  Celestial_Abyssal: "Celestial or abyssal",
  Charged_Electric: "Charged tension",
  Clean_Prose: "Clean prose",
  Clipped_Rapid: "Fast and clipped",
  Code_Block_Shielding: "Protected code blocks",
  Collective_AU: "Group AU",
  Combative_Friction: "Argument or friction",
  Constant_Anchor: "Always available",
  Contained_Insular: "Closed-in setting",
  Corporate_Finance: "Corporate or finance",
  Corporate_Institutional: "Workplace or institution",
  Creative_Public: "Creative or public-facing",
  "Cruel Prince / Aloof Aristocrat": "Cruel prince / aloof aristocrat",
  "Dark/Possessive Anti-Hero": "Dark / possessive anti-hero",
  Defiant_Autonomy: "Defiant independence",
  Dependent_Protected: "Protected or dependent",
  Devoted_Loyal: "Devoted and loyal",
  Diaspora_Blended: "Mixed diaspora background",
  "Diasporic Shift": "Different from background",
  "Double / Hyphenated": "Double or hyphenated",
  Dynamic_User_Sliders: "User-controlled sliders",
  Dynamic_Variable_Loop: "Dynamic variables",
  Eastern_European_Slavic: "Eastern European or Slavic",
  East_Southeast_Asian: "East or Southeast Asian",
  Equal: "Equal",
  Environmental_Anchor: "Setting anchor",
  EU_Schengen: "EU / Schengen",
  Expat_Visa: "Expat or visa holder",
  Exhibitionism_Risk: "Risk of being seen",
  Extended_Deep_Lore: "Extended deep lore",
  Extreme_Height_Gap: "Extreme height gap",
  Fae_Immortal_Folk: "Fae or immortal folk",
  Family_Lineage: "Family connection",
  Fated_Mates_Soul_Bonds: "Fated mates or soul bonds",
  Feet_Footwear: "Feet or footwear",
  Fictional_Empire: "Fictional country or empire",
  "First Name": "First name",
  First_Generation_Immigrant: "First-generation immigrant",
  First_Person_I: "1st POV Present",
  Fixed_Mortal: "Normal mortal lifespan",
  Formal_Chilling: "Formal and tense",
  Formal_Poetic: "Formal and poetic",
  Found_Family: "Found family",
  Fully_Open: "Open to love",
  Geopolitical_Faction: "Faction or politics",
  Glamour_Seduction_Aura: "Glamour or seductive aura",
  Gritty_Melodramatic: "Gritty and dramatic",
  Guarded_Closed: "Guarded",
  "Gaelic & Celtic": "Gaelic or Celtic",
  "Germanic & Nordic": "Germanic or Nordic",
  "Gritty / Edgy": "Gritty or edgy",
  High_Intensity_Dirty: "High-intensity dirty talk",
  High_Professional: "High-status professional",
  High_Taboo: "High scandal risk",
  "Historical Regency Anchor": "Historical / Regency",
  "Historical Medieval Anchor": "Historical / Medieval",
  Homogeneous_Alignment: "Matches their background",
  "Homogeneous Alignment": "Matches their background",
  Humanities_Law: "Humanities or law",
  Hyper_Charm_Deflection: "Deflects with charm",
  Hyper_Independence: "Hyper-independent",
  Hyper_Rationalization: "Over-rationalizes",
  Indigenous_First_Nations: "Indigenous / First Nations",
  "Indigenous / Native Home Ground": "Native to this setting",
  Intense_Devoted: "Intense and devoted",
  Intense_Heavy: "Intense",
  Internal_Fracture: "Internal conflict",
  Internal_Monologue_Heavy: "Heavy inner monologue",
  Jaded_Resignation: "Jaded resignation",
  Jaded_Weary: "Jaded and weary",
  Lace_Silk: "Lace or silk",
  Leather_Latex: "Leather or latex",
  Lighthearted_Wholesome: "Light and wholesome",
  Lingering_Past: "Past still matters",
  "Latinate / Romance": "Latinate or Romance language",
  "Low_Gossip": "Low gossip risk",
  Love_Triangle_Rivalry: "Love triangle rivalry",
  Medical_Science: "Medical or science",
  Measured_Deliberate: "Measured and deliberate",
  Micro_Macro_Scale: "Micro / macro scale",
  Middle_Eastern_North_African: "Middle Eastern or North African",
  Mild_Vanilla: "Mild / vanilla",
  Moderate_Sensory: "Moderate sensory",
  Monolithic_System_Prompt: "Single system prompt",
  Mortal_Baseline: "Mortal baseline",
  Multigenerational_Diaspora: "Multigenerational diaspora",
  Multiracial_Blended: "Multiracial / blended",
  Mythological_Rules: "Mythology rules",
  Naturalized: "Naturalized citizen",
  Natural_Language: "Natural language",
  No_Role_Reversal: "No role reversal",
  No_Rushed_Pacing: "No rushed pacing",
  No_Unprompted_Aggression: "No unprompted aggression",
  Non_EU_European: "Non-EU European",
  Northern_Western_European: "Northern or Western European",
  Optimistic_Idealistic: "Optimistic and idealistic",
  Outsider: "Outsider",
  Paragraph_Isolated: "Separate paragraphs",
  People_Pleasing_Inversion: "People-pleasing",
  Phenotypic_Palette_Focus: "Appearance-focused",
  "Phenotypic Palette Focus": "Appearance-focused",
  Playful_Teasing: "Playful teasing",
  Post_Crisis_Quiet: "Quiet after a crisis",
  Praise_Validation: "Praise and validation",
  Professional_Circle: "Professional contact",
  Public_HighExposure: "Public place",
  Quote_Isolated_Prose: "Dialogue tag",
  Raw_Agnostic_JSON: "Platform-neutral JSON",
  Raw_Script: "Script style",
  Reactive_Contextual: "Only when relevant",
  Recursive_Linked: "Can trigger other lore",
  Ruthless_Cynical: "Ruthless and cynical",
  Second_Person_Direct: "2nd POV Direct",
  Segmented_Placements: "Section-by-section placement",
  Self_Funded: "Self-funded",
  Silent_Connection: "Quiet connection",
  Silent_Withdrawal: "Silent withdrawal",
  Slavic_Cyrillic_Derived: "Slavic or Cyrillic-derived",
  Slow_Tease_Prose: "Slow tease",
  Societal_Customs: "Social customs",
  Southern_European: "Southern European",
  South_Central_Asian: "South or Central Asian",
  Standard_Scale: "Standard scale",
  Status_Valve: "Status shift",
  STEM_Medical: "STEM or medicine",
  Stoic_Restrained: "Stoic and restrained",
  Strained_Fractured: "Strained",
  Third_Person_Past: "3rd POV Past",
  Third_Person_Present: "3rd POV Present",
  The_Ancient_Predator: "Ancient predator",
  The_Approach: "The approach",
  The_Barrier: "The barrier",
  The_Broken_Heir: "Broken heir",
  The_Chance_Encounter: "Chance encounter",
  The_Confessor: "Confessor",
  The_Crisis: "Crisis",
  The_Fae_Deal_Maker: "Deal maker",
  The_Golden_Retriever: "Golden retriever",
  The_Hunger_Feed_Dynamics: "Hunger or feeding instincts",
  The_Jealousy_Instigator: "Jealousy instigator",
  The_Mandate: "Forced together",
  The_Matchmaker: "Matchmaker",
  The_Nurturer: "Nurturer",
  The_Perfectionist: "Perfectionist",
  The_Processor: "Processor",
  The_Quiet_Guardian: "Quiet guardian",
  The_Rogue_Instigator: "Rogue instigator",
  The_Ruthless_Architect: "Ruthless planner",
  The_Secret_Keeper: "Secret keeper",
  The_Seeker: "Seeker",
  The_Stoic_Wall: "Stoic wall",
  The_Vigilante_Outcast: "Vigilante outcast",
  Therianthrope_Shifter: "Shifter",
  Thighs_Midriff: "Thighs or midriff",
  Timeline_Link: "Timeline link",
  Timeline_Shift: "Timeline shift",
  Tone_Escalation: "Tone shift",
  Touch_Holding: "Touch and holding",
  "Traumatized/Protected Soul": "Protected wounded soul",
  Ultra_Elite: "Ultra-elite",
  Ultra_Lean_Context: "Lean context",
  Universe_AU: "AU / alternate world",
  Uniforms_Suits: "Uniforms or suits",
  Validation_Approval: "Validation and approval",
  Vengeance_Claiming: "Vengeance or claiming",
  Vengeance_Redress: "Vengeance or redress",
  Verbal_Affirmation: "Verbal affirmation",
  Vulnerability_Martyrdom: "Vulnerability martyrdom",
  Vulnerability_Sleep: "Vulnerability or sleep",
  Vulnerable_Exhausted: "Vulnerable and exhausted",
  Vulnerable_Yielding: "Vulnerable and yielding",
  V2_Card_Standard: "V2 card standard",
  V3_Card_Layout: "V3 card layout",
  Vercel_Structured_Zod: "Structured app schema",
  Western_Allies: "Western-allied countries",
  Weighted_Bold_Impact: "Bold emphasis",
  Weighted_StandOff: "Loaded stand-off",
  White_Caucasian: "White / Caucasian",
  Working_Class: "Working class",
  W_PlusPlus: "W++ format",
  "W++": "W++ format",
  Boostyle: "Boostyle format",
  JSON: "JSON format",
  "Natural Language": "Natural language",
};

export function humanizeOptionLabel(value: string) {
  const mappedLabel = USER_FACING_OPTION_LABELS[value];

  if (mappedLabel) {
    return mappedLabel;
  }

  return value
    .replace(/^Asymmetric\s+/, "")
    .replace(/([a-z])([A-Z])/g, "$1 $2")
    .replace(/_/g, " ")
    .replace(/\bAi\b/g, "AI")
    .replace(/\bJson\b/g, "JSON")
    .replace(/\bNpc\b/g, "NPC")
    .replace(/\bPov\b/g, "POV")
    .replace(/\bRpg\b/g, "RPG")
    .replace(/\bCta\b/g, "CTA")
    .replace(/\bEu\b/g, "EU")
    .replace(/\bNb\b/g, "NB")
    .replace(/\bId\b/g, "ID")
    .replace(/\bV([23])\b/g, "V$1");
}
