import type { RomanceTropeClass } from "./character-card/RomanceTropeClassification";

export type TropeViewportConfig = {
  label: string;
  border: string;
  bubble: string;
  glow: string;
  headerText: string;
  screenVignette: string;
};

export const COMPLETE_TROPE_MATRIX: Record<
  RomanceTropeClass,
  TropeViewportConfig
> = {
  antagonistic: {
    label: "Rival Friction",
    border: "border-red-500/30",
    bubble: "from-red-950/18 via-transparent",
    glow: "shadow-red-950/20",
    headerText: "text-red-300",
    screenVignette: "from-red-950/22 via-transparent",
  },
  bantering: {
    label: "Playful Banter",
    border: "border-amber-500/30",
    bubble: "from-amber-950/15 via-transparent",
    glow: "shadow-amber-950/20",
    headerText: "text-amber-300",
    screenVignette: "from-amber-950/18 via-transparent",
  },
  bound: {
    label: "Bound Together",
    border: "border-stone-500/30",
    bubble: "from-stone-950/20 via-transparent",
    glow: "shadow-stone-950/20",
    headerText: "text-stone-300",
    screenVignette: "from-stone-950/20 via-transparent",
  },
  casual: {
    label: "Neutral Focus",
    border: "border-[var(--panel-border)]",
    bubble: "from-transparent",
    glow: "shadow-transparent",
    headerText: "text-[var(--muted)]",
    screenVignette: "from-transparent",
  },
  commanding: {
    label: "Commanding Pressure",
    border: "border-orange-500/30",
    bubble: "from-orange-950/18 via-transparent",
    glow: "shadow-orange-950/20",
    headerText: "text-orange-300",
    screenVignette: "from-orange-950/20 via-transparent",
  },
  defeating: {
    label: "Defeating Odds",
    border: "border-slate-500/30",
    bubble: "from-slate-950/25 via-transparent",
    glow: "shadow-slate-950/20",
    headerText: "text-slate-300",
    screenVignette: "from-slate-950/24 via-transparent",
  },
  deferential: {
    label: "Deferential Courtesy",
    border: "border-violet-500/30",
    bubble: "from-violet-950/16 via-transparent",
    glow: "shadow-violet-950/20",
    headerText: "text-violet-300",
    screenVignette: "from-violet-950/18 via-transparent",
  },
  estranged: {
    label: "Estranged Distance",
    border: "border-sky-500/30",
    bubble: "from-sky-950/16 via-transparent",
    glow: "shadow-sky-950/20",
    headerText: "text-sky-300",
    screenVignette: "from-sky-950/18 via-transparent",
  },
  familiar: {
    label: "Old Familiarity",
    border: "border-emerald-500/30",
    bubble: "from-emerald-950/16 via-transparent",
    glow: "shadow-emerald-950/20",
    headerText: "text-emerald-300",
    screenVignette: "from-emerald-950/18 via-transparent",
  },
  flustered: {
    label: "Flustered Tension",
    border: "border-pink-500/30",
    bubble: "from-pink-950/20 via-transparent",
    glow: "shadow-pink-950/25",
    headerText: "text-pink-300",
    screenVignette: "from-pink-950/24 via-transparent",
  },
  forbidden: {
    label: "Forbidden Pull",
    border: "border-purple-500/30",
    bubble: "from-purple-950/22 via-transparent",
    glow: "shadow-purple-950/25",
    headerText: "text-purple-300",
    screenVignette: "from-purple-950/26 via-transparent",
  },
  grudging: {
    label: "Grudging Respect",
    border: "border-lime-500/30",
    bubble: "from-lime-950/14 via-transparent",
    glow: "shadow-lime-950/20",
    headerText: "text-lime-300",
    screenVignette: "from-lime-950/16 via-transparent",
  },
  grumpy: {
    label: "Grumpy Guard",
    border: "border-zinc-500/30",
    bubble: "from-zinc-950/24 via-transparent",
    glow: "shadow-zinc-950/20",
    headerText: "text-zinc-300",
    screenVignette: "from-zinc-950/24 via-transparent",
  },
  haunted: {
    label: "Haunted Past",
    border: "border-indigo-500/30",
    bubble: "from-indigo-950/22 via-transparent",
    glow: "shadow-indigo-950/25",
    headerText: "text-indigo-300",
    screenVignette: "from-indigo-950/24 via-transparent",
  },
  performative: {
    label: "Public Performance",
    border: "border-fuchsia-500/30",
    bubble: "from-fuchsia-950/16 via-transparent",
    glow: "shadow-fuchsia-950/20",
    headerText: "text-fuchsia-300",
    screenVignette: "from-fuchsia-950/18 via-transparent",
  },
  protective: {
    label: "Protective Heat",
    border: "border-rose-500/35",
    bubble: "from-rose-950/24 via-transparent",
    glow: "shadow-rose-950/30",
    headerText: "text-rose-300",
    screenVignette: "from-rose-950/28 via-transparent",
  },
  reclaiming: {
    label: "Reclaiming Bond",
    border: "border-teal-500/30",
    bubble: "from-teal-950/18 via-transparent",
    glow: "shadow-teal-950/20",
    headerText: "text-teal-300",
    screenVignette: "from-teal-950/20 via-transparent",
  },
  recognized: {
    label: "Soul Recognition",
    border: "border-violet-400/35",
    bubble: "from-violet-950/24 via-transparent",
    glow: "shadow-violet-950/30",
    headerText: "text-violet-300",
    screenVignette: "from-violet-950/28 via-transparent",
  },
  secretive: {
    label: "Secretive Risk",
    border: "border-cyan-500/30",
    bubble: "from-cyan-950/16 via-transparent",
    glow: "shadow-cyan-950/20",
    headerText: "text-cyan-300",
    screenVignette: "from-cyan-950/18 via-transparent",
  },
  slipped_mask: {
    label: "Slipped Mask",
    border: "border-blue-500/30",
    bubble: "from-blue-950/18 via-transparent",
    glow: "shadow-blue-950/20",
    headerText: "text-blue-300",
    screenVignette: "from-blue-950/20 via-transparent",
  },
  smothered: {
    label: "Too Close",
    border: "border-cyan-400/30",
    bubble: "from-cyan-950/20 via-transparent",
    glow: "shadow-cyan-950/20",
    headerText: "text-cyan-200",
    screenVignette: "from-cyan-950/22 via-transparent",
  },
  sunshine: {
    label: "Sunshine Lift",
    border: "border-yellow-400/30",
    bubble: "from-yellow-950/14 via-transparent",
    glow: "shadow-yellow-950/20",
    headerText: "text-yellow-300",
    screenVignette: "from-yellow-950/16 via-transparent",
  },
  thawing: {
    label: "Thawing Guard",
    border: "border-emerald-400/30",
    bubble: "from-emerald-950/18 via-transparent",
    glow: "shadow-emerald-950/20",
    headerText: "text-emerald-300",
    screenVignette: "from-emerald-950/20 via-transparent",
  },
  trucetaking: {
    label: "Fragile Truce",
    border: "border-stone-400/30",
    bubble: "from-stone-950/16 via-transparent",
    glow: "shadow-stone-950/20",
    headerText: "text-stone-300",
    screenVignette: "from-stone-950/18 via-transparent",
  },
  yearning: {
    label: "Quiet Yearning",
    border: "border-fuchsia-500/30",
    bubble: "from-fuchsia-950/22 via-transparent",
    glow: "shadow-fuchsia-950/25",
    headerText: "text-fuchsia-300",
    screenVignette: "from-fuchsia-950/24 via-transparent",
  },
};
