insert into public.category_tags (id, group_name, label, slug, description)
values
  ('tag-brothers-best-friend', 'trope', 'Brother''s Best Friend', 'brothers-best-friend', null),
  ('tag-brothers-girlfriend', 'trope', 'Brother''s Girlfriend', 'brothers-girlfriend', null),
  ('tag-brothers-boyfriend', 'trope', 'Brother''s Boyfriend', 'brothers-boyfriend', null),
  ('tag-sisters-best-friend', 'trope', 'Sister''s Best Friend', 'sisters-best-friend', null),
  ('tag-sisters-girlfriend', 'trope', 'Sister''s Girlfriend', 'sisters-girlfriend', null),
  ('tag-sisters-boyfriend', 'trope', 'Sister''s Boyfriend', 'sisters-boyfriend', null),
  ('tag-best-friends-best-friend', 'trope', 'Best Friend''s Best Friend', 'best-friends-best-friend', null),
  ('tag-best-friends-girlfriend', 'trope', 'Best Friend''s Girlfriend', 'best-friends-girlfriend', null),
  ('tag-best-friends-boyfriend', 'trope', 'Best Friend''s Boyfriend', 'best-friends-boyfriend', null),
  ('tag-enemies-to-lovers', 'trope', 'Enemies to Lovers', 'enemies-to-lovers', null),
  ('tag-friends-to-lovers', 'trope', 'Friends to Lovers', 'friends-to-lovers', null),
  ('tag-exes', 'trope', 'Exes', 'exes', null),
  ('tag-missed-connections', 'trope', 'Missed Connections', 'missed-connections', null),
  ('tag-secret-relationship', 'trope', 'Secret Relationship', 'secret-relationship', null),
  ('tag-step-siblings', 'trope', 'Step Siblings', 'step-siblings', null),
  ('tag-age-gap', 'trope', 'Age Gap', 'age-gap', null),
  ('tag-marriage-of-convenience', 'trope', 'Marriage of Convenience', 'marriage-of-convenience', null),
  ('tag-betrothal', 'trope', 'Betrothal', 'betrothal', null),
  ('tag-fake-dating', 'trope', 'Fake Dating', 'fake-dating', null),
  ('tag-omegaverse', 'trope', 'Omegaverse', 'omegaverse', null),
  ('tag-vampire', 'trope', 'Vampire', 'vampire', null),
  ('tag-werewolf', 'trope', 'Werewolf', 'werewolf', null),
  ('tag-sci-fi', 'trope', 'Sci-Fi', 'sci-fi', null),
  ('tag-situationship', 'trope', 'Situationship', 'situationship', 'Undefined relationship with emotional leverage and unclear claims.'),
  ('tag-possessive', 'relationship_dynamic', 'Possessive', 'possessive', null),
  ('tag-obsessive', 'relationship_dynamic', 'Obsessive', 'obsessive', null),
  ('tag-dominant-submissive', 'relationship_dynamic', 'Dominant/submissive', 'dominant-submissive', null),
  ('tag-switch-submissive', 'relationship_dynamic', 'Switch/submissive', 'switch-submissive', null),
  ('tag-competitive', 'relationship_dynamic', 'Competitive', 'competitive', null),
  ('tag-menage', 'relationship_dynamic', 'Menage', 'menage', null),
  ('tag-polycule', 'relationship_dynamic', 'Polycule', 'polycule', null),
  ('tag-opposites-attract', 'relationship_dynamic', 'Opposites Attract', 'opposites-attract', null),
  ('tag-class-disparity', 'relationship_dynamic', 'Class Disparity', 'class-disparity', null),
  ('tag-hurt-comfort', 'relationship_dynamic', 'Hurt/Comfort', 'hurt-comfort', null),
  ('tag-grumpy-sunshine', 'relationship_dynamic', 'Grumpy/Sunshine', 'grumpy-sunshine', null),
  ('tag-one-night-stand', 'relationship_dynamic', 'One Night Stand', 'one-night-stand', null),
  ('tag-fwb', 'relationship_dynamic', 'FWB', 'fwb', null),
  ('tag-mutual-longing', 'relationship_dynamic', 'Mutual Longing', 'mutual-longing', null),
  ('tag-one-sided-pining', 'relationship_dynamic', 'One-Sided Pining', 'one-sided-pining', null),
  ('tag-aro-ace', 'relationship_dynamic', 'Aro/Ace', 'aro-ace', null),
  ('tag-pg13', 'heat_intimacy_mode', 'PG13', 'pg13', null),
  ('tag-nc17', 'heat_intimacy_mode', 'NC17', 'nc17', null),
  ('tag-r18-plus', 'heat_intimacy_mode', 'R18+', 'r18-plus', null),
  ('tag-fempov', 'pov', 'FemPOV', 'fempov', null),
  ('tag-malepov', 'pov', 'MalePOV', 'malepov', null),
  ('tag-anypov', 'pov', 'AnyPOV', 'anypov', null),
  ('tag-storymode', 'pov', 'StoryMode', 'storymode', null),
  ('tag-writingstyle', 'writing_style', 'WritingStyle', 'writingstyle', null),
  ('tag-janitorai', 'platform_export_target', 'JanitorAI', 'janitorai', null),
  ('tag-sillytavern', 'platform_export_target', 'SillyTavern', 'sillytavern', null),
  ('tag-marinaratavern', 'platform_export_target', 'MarinaraTavern', 'marinaratavern', null),
  ('tag-blocked', 'content_boundary', 'Blocked', 'blocked', null)
on conflict (slug) do update set
  group_name = excluded.group_name,
  label = excluded.label,
  description = excluded.description,
  updated_at = now();

insert into public.core_prompt_packs (
  id,
  title,
  slug,
  category,
  description,
  base_prompt,
  compatible_tag_slugs,
  default_platform_targets
)
values
  (
    'core-changing-perspectives',
    'Changing Perspectives',
    'changing-perspectives',
    'Trope core',
    'For enemies-to-lovers, friends-to-lovers, and shifting emotional read.',
    'Track what each character believes, what they refuse to say, and what the active POV is allowed to know. Let changed behavior prove the shift before anyone explains it.',
    array['enemies-to-lovers', 'friends-to-lovers'],
    array['JanitorAI', 'SillyTavern', 'MarinaraTavern']
  ),
  (
    'core-second-chance-romance',
    'Second Chance Romance',
    'second-chance-romance',
    'Trope core',
    'For exes, missed connections, and almost-happened relationships with unfinished emotional business.',
    'Let the past create pressure without resolving itself too quickly. Keep regret, changed circumstances, and the difference between remembered intimacy and present trust active in the scene.',
    array['exes', 'missed-connections'],
    array['JanitorAI', 'SillyTavern', 'MarinaraTavern']
  ),
  (
    'core-forbidden-attraction',
    'Forbidden Attraction',
    'forbidden-attraction',
    'Boundary core',
    'For secret relationships, friend or sibling adjacency, step-sibling tension, and age-gap pressure.',
    'Frame the attraction through consequence, secrecy, proximity, and social cost. Preserve consent, agency, and plausible reasons the characters hesitate, hide, deny, or risk exposure.',
    array[
      'secret-relationship',
      'brothers-best-friend',
      'brothers-girlfriend',
      'brothers-boyfriend',
      'sisters-best-friend',
      'sisters-girlfriend',
      'sisters-boyfriend',
      'best-friends-best-friend',
      'best-friends-girlfriend',
      'best-friends-boyfriend',
      'step-siblings',
      'age-gap'
    ],
    array['JanitorAI', 'SillyTavern', 'MarinaraTavern']
  ),
  (
    'core-arranged-marriage',
    'Arranged Marriage',
    'arranged-marriage',
    'Relationship core',
    'For marriage of convenience, betrothal, fake dating, and public/private contract pressure.',
    'Treat the arrangement as a social machine with private emotional fallout. Track what is performed publicly, what is negotiated privately, and what becomes real before anyone is ready to admit it.',
    array['marriage-of-convenience', 'betrothal', 'fake-dating'],
    array['JanitorAI', 'SillyTavern', 'MarinaraTavern']
  ),
  (
    'core-dark-romance',
    'Dark Romance',
    'dark-romance',
    'Intensity core',
    'For morally grey, possessive, obsessive, or degradation-compatible dynamics.',
    'Keep intensity rooted in character motive, negotiated boundaries, consequence, and power exchange. Do not flatten possessiveness into generic aggression.',
    array['possessive', 'obsessive'],
    array['JanitorAI', 'SillyTavern', 'MarinaraTavern']
  ),
  (
    'core-supernatural',
    'Supernatural',
    'supernatural',
    'World core',
    'For omegaverse, vampire, werewolf, and sci-fi premises where biology, world rules, or genre logic shape intimacy.',
    'Make the speculative rule matter in-scene through behavior, consequence, social structure, sensory pressure, or power imbalance. Keep world logic readable and character desire specific.',
    array['omegaverse', 'vampire', 'werewolf', 'sci-fi'],
    array['JanitorAI', 'SillyTavern', 'MarinaraTavern']
  ),
  (
    'core-bdsm-dynamics',
    'BDSM Dynamics',
    'bdsm-dynamics',
    'Dynamic core',
    'For dom/sub, switch, praise, daddy, DDLG, and degradation-compatible relationship dynamics.',
    'Write power exchange as behavior, trust, consent, correction, reward, restraint, permission, refusal, and aftermath. Match the dynamic to the characters instead of using a generic dominant script.',
    array['dominant-submissive', 'switch-submissive'],
    array['JanitorAI', 'SillyTavern', 'MarinaraTavern']
  ),
  (
    'core-non-traditional-relationships',
    'Non-Traditional Relationships',
    'non-traditional-relationships',
    'Relationship core',
    'For aro/ace, polycule, menage, and other relationship structures that need clear expectations and agency.',
    'Keep the relationship structure explicit enough to prevent assumptions. Track consent, agreements, jealousy, unmet needs, and how each person defines intimacy, commitment, or distance.',
    array['aro-ace', 'polycule', 'menage'],
    array['JanitorAI', 'SillyTavern', 'MarinaraTavern']
  ),
  (
    'core-messy-relationships',
    'Love Triangles + Messy Relationships',
    'love-triangles-messy-relationships',
    'Relationship core',
    'For situationships, FWB, mutual longing, one-sided pining, and asymmetric secrets.',
    'Treat the relationship as active pressure. Preserve asymmetric knowledge, unresolved longing, and the difference between public behavior and private motive.',
    array['situationship', 'fwb', 'mutual-longing', 'one-sided-pining', 'one-night-stand'],
    array['JanitorAI', 'SillyTavern', 'MarinaraTavern']
  )
on conflict (slug) do update set
  title = excluded.title,
  category = excluded.category,
  description = excluded.description,
  base_prompt = excluded.base_prompt,
  compatible_tag_slugs = excluded.compatible_tag_slugs,
  default_platform_targets = excluded.default_platform_targets,
  updated_at = now();
