export type ContemporaryWorldSeedScope =
  | "character_book"
  | "memory_book"
  | "prompt_book"
  | "scenario_book"
  | "user_book"
  | "world_book";

export interface ContemporaryWorldVocabularySeed {
  slug: string;
  label: string;
  scope: ContemporaryWorldSeedScope[];
  fictionLabels: string[];
  routeTags: string[];
  vocabularySeeds: string[];
  triggerSeeds: string[];
  compilerHints: string[];
  antiPatterns: string[];
}

export const contemporaryWorldVocabularySeeds: ContemporaryWorldVocabularySeed[] = [
  {
    slug: "ambient_technology",
    label: "Everyday technology texture",
    scope: ["world_book", "scenario_book", "prompt_book"],
    fictionLabels: ["phone weather", "screen glow", "ordinary digital life"],
    routeTags: [
      "technology_baseline",
      "modern_texture",
      "ambient_world_detail",
      "contemporary_setting",
    ],
    vocabularySeeds: [
      "phone buzz",
      "screen glow",
      "typing indicator",
      "seen receipt",
      "muted chat",
      "voice note",
      "pinned message",
      "shared album",
      "charging cable",
      "smartwatch tap",
      "earbud silence",
      "laptop light",
    ],
    triggerSeeds: [
      "visibly online",
      "left on read",
      "phone face-down",
      "edited message",
      "missed call",
      "do not disturb",
      "message reaction",
      "old photo like",
    ],
    compilerHints: [
      "Use technology when it changes access, timing, intimacy, secrecy, evidence, jealousy, or social consequence.",
      "Keep devices casual and lived-in unless a digital trace changes the scene pressure.",
      "Prefer one meaningful digital detail over a checklist of modern props.",
    ],
    antiPatterns: [
      "Do not make every scene about the phone because phones exist.",
      "Do not treat digital evidence as omniscient or instantly available.",
    ],
  },
  {
    slug: "digital_visibility",
    label: "Digital visibility and privacy",
    scope: ["world_book", "scenario_book", "memory_book", "prompt_book"],
    fictionLabels: ["receipts and receipts", "private until screens prove otherwise"],
    routeTags: [
      "digital_residue",
      "privacy_exposure_risk",
      "secret_pressure",
      "evidence_pressure",
    ],
    vocabularySeeds: [
      "screenshot",
      "cloud backup",
      "location history",
      "mutual followers",
      "shared calendar",
      "blocked contact",
      "private browsing",
      "two-factor code",
      "deleted thread",
      "metadata trail",
      "rideshare log",
      "workplace device",
    ],
    triggerSeeds: [
      "deleted but remembered",
      "screenshot saved",
      "location sharing still on",
      "camera in the hallway",
      "shared calendar invite",
      "blocked then unblocked",
      "profile change",
      "post removed",
    ],
    compilerHints: [
      "Separate confirmed evidence, suspected evidence, misread behavior, hidden records, and public fallout.",
      "Let secrecy become difficult through traces, witnesses, logs, and public-facing personas.",
      "Use digital privacy as pressure, not exposition.",
    ],
    antiPatterns: [
      "Do not let a character know a private digital fact without a plausible trace.",
      "Do not turn privacy systems into a lore dump.",
    ],
  },
  {
    slug: "relationship_official_status",
    label: "Relationship official status",
    scope: ["world_book", "scenario_book", "memory_book", "character_book", "user_book"],
    fictionLabels: ["public or private", "soft launch", "paper official"],
    routeTags: [
      "relationship_visibility",
      "public_private_boundary",
      "official_status",
      "social_risk",
    ],
    vocabularySeeds: [
      "soft launch",
      "public introduction",
      "relationship status",
      "family recognition",
      "shared lease",
      "shared finances",
      "workplace disclosure",
      "domestic partnership",
      "insurance paperwork",
      "tax records",
      "public claim",
      "private arrangement",
    ],
    triggerSeeds: [
      "introduce me as",
      "changed status",
      "moved in together",
      "kept off the invite",
      "not telling family",
      "workplace disclosure form",
      "shared address",
      "posted together",
    ],
    compilerHints: [
      "Track whether the relationship is emotionally real, publicly visible, legally visible, or deliberately hidden.",
      "Let fake dating and secret relationships conflict with paperwork, family rituals, and social media visibility.",
      "Store public recognition changes as Memory Book residue.",
    ],
    antiPatterns: [
      "Do not assume emotional commitment and public recognition are the same state.",
      "Do not make secrecy cost-free when the world has visibility systems.",
    ],
  },
  {
    slug: "legal_contract_pressure",
    label: "Legal and contract pressure",
    scope: ["world_book", "scenario_book", "memory_book", "prompt_book"],
    fictionLabels: ["paper trail", "signed lines", "official pressure"],
    routeTags: [
      "legal_pressure",
      "contract_pressure",
      "institutional_boundary",
      "authority_system",
    ],
    vocabularySeeds: [
      "NDA",
      "employee handbook",
      "HR email",
      "morality clause",
      "lease clause",
      "prenup",
      "trust document",
      "will reading",
      "scholarship condition",
      "visa condition",
      "custody paperwork",
      "calendar invite",
    ],
    triggerSeeds: [
      "sign this",
      "HR wants a meeting",
      "contract says",
      "lawyer called",
      "paperwork deadline",
      "workplace policy",
      "family lawyer",
      "locked file",
    ],
    compilerHints: [
      "Show institutional pressure through forms, meetings, locked files, emails, lawyers, gossip, and scheduled consequences.",
      "Use contracts to constrain choices, not to replace character motivation.",
      "Keep the rule concrete and scene-relevant.",
    ],
    antiPatterns: [
      "Do not dump an entire policy unless the user asks.",
      "Do not use legal pressure as random drama when no existing system supports it.",
    ],
  },
  {
    slug: "money_housing_class_pressure",
    label: "Money, housing, and class pressure",
    scope: ["world_book", "scenario_book", "memory_book", "character_book", "user_book"],
    fictionLabels: ["who can leave", "what help costs", "rooms money buys"],
    routeTags: [
      "economic_pressure",
      "class_pressure",
      "housing_pressure",
      "resource_constraint",
      "autonomy_pressure",
    ],
    vocabularySeeds: [
      "rent",
      "housing shortage",
      "student loans",
      "medical bill",
      "gig shift",
      "unstable roster",
      "shared lease",
      "co-signed loan",
      "trust fund",
      "inheritance",
      "private car",
      "failing bus route",
      "security deposit",
      "family support obligation",
    ],
    triggerSeeds: [
      "can't afford",
      "missed rent",
      "loan payment",
      "shift starts soon",
      "last train",
      "offered to pay",
      "shared address",
      "inheritance condition",
    ],
    compilerHints: [
      "Let money change privacy, rest, transport, exit options, scandal risk, and whether help feels loving or controlling.",
      "Track financial pride, shame, dependence, and rescue fantasies per character.",
      "Use concrete costs and access limits instead of vague rich/poor flavor.",
    ],
    antiPatterns: [
      "Do not let wealth solve every problem without creating agency friction.",
      "Do not keep money abstract when it should change the scene options.",
    ],
  },
  {
    slug: "location_pressure",
    label: "Location pressure",
    scope: ["world_book", "scenario_book", "memory_book", "prompt_book"],
    fictionLabels: ["the room has rules", "thin walls", "no easy exit"],
    routeTags: [
      "location_pressure",
      "spatial_constraint",
      "proximity_engine",
      "witness_risk",
      "escape_barrier",
    ],
    vocabularySeeds: [
      "thin walls",
      "back stairwell",
      "locked office",
      "single cabin",
      "shared lease",
      "hotel corridor",
      "quiet gallery corner",
      "campus hallway",
      "clinic waiting room",
      "public transport",
      "country retreat",
      "weather-locked shelter",
    ],
    triggerSeeds: [
      "door won't lock",
      "someone could hear",
      "only one bed",
      "storm blocked the road",
      "last train left",
      "security cameras",
      "family downstairs",
      "office glass walls",
    ],
    compilerHints: [
      "Treat locations as pressure engines: privacy, acoustics, lighting, temperature, scent, witness risk, control, resources, exits, and residue.",
      "Use setting to enforce trope logic such as forced proximity, forbidden attraction, class gap, secrecy, and public/private contrast.",
      "Carry location history forward when a place becomes emotionally loaded.",
    ],
    antiPatterns: [
      "Do not use location as wallpaper.",
      "Do not add setting details that never alter access, privacy, proximity, timing, or consequence.",
    ],
  },
  {
    slug: "time_texture",
    label: "Time texture",
    scope: ["world_book", "scenario_book", "memory_book", "prompt_book"],
    fictionLabels: ["time has weather", "the hour changes the room"],
    routeTags: [
      "time_texture",
      "scene_timing",
      "body_state",
      "environmental_continuity",
    ],
    vocabularySeeds: [
      "early light",
      "coffee smell",
      "first traffic",
      "work tempo",
      "short shadows",
      "commute residue",
      "windows glowing",
      "cooling air",
      "long shadows",
      "isolated sound",
      "pooled darkness",
      "night silence",
    ],
    triggerSeeds: [
      "morning after",
      "shift change",
      "deadline approaching",
      "last train",
      "late enough",
      "hours passed",
      "sun coming up",
      "too tired to argue",
    ],
    compilerHints: [
      "Embed time through action, light, sound, temperature, body state, routines, and fatigue.",
      "Use time to make delay, recovery, sleep, hunger, commute, missed chances, and obligations matter.",
      "Let emotional residue decay naturally rather than resetting between scenes.",
    ],
    antiPatterns: [
      "Do not list atmospheric details as decoration.",
      "Do not reset bodies or emotions just because the scene changed.",
    ],
  },
  {
    slug: "world_intrusion_cadence",
    label: "World intrusion cadence",
    scope: ["scenario_book", "prompt_book", "memory_book"],
    fictionLabels: ["pressure is continuous, not constant", "the world waits its turn"],
    routeTags: [
      "world_intrusion_cadence",
      "active_pressure",
      "existing_tension",
      "consequence_timing",
    ],
    vocabularySeeds: [
      "deadline",
      "interruption",
      "obligation",
      "resource pinch",
      "witness arrival",
      "weather shift",
      "fatigue",
      "social risk",
      "unanswered message",
      "quiet consequence",
      "earned interruption",
      "unsurfaced pressure",
    ],
    triggerSeeds: [
      "time has passed",
      "stillness stretches",
      "someone knocks",
      "phone buzzes again",
      "deadline hits",
      "body gives out",
      "rumor spreads",
      "choice costs something",
    ],
    compilerHints: [
      "Activate existing pressure before inventing a new event.",
      "Let the world assert itself when time, resources, location, body state, social pressure, or character attention makes inaction costly.",
      "Leave tense exchanges room to breathe when existing pressure is already enough.",
    ],
    antiPatterns: [
      "Do not add a new interruption every response.",
      "Do not inject drama when wounds, deadlines, secrecy, money, fatigue, social risk, or desire are already available.",
    ],
  },
  {
    slug: "healthcare_reproductive_pressure",
    label: "Healthcare and reproductive pressure",
    scope: ["world_book", "scenario_book", "memory_book", "prompt_book"],
    fictionLabels: ["body autonomy stakes", "private healthcare pressure"],
    routeTags: [
      "healthcare_access",
      "reproductive_trope_pressure",
      "privacy_pressure",
      "agency_sensitive",
    ],
    vocabularySeeds: [
      "contraception access",
      "healthcare cost",
      "clinic appointment",
      "pharmacy counter",
      "medical bill",
      "family pressure",
      "inheritance stakes",
      "public judgment",
      "bodily autonomy",
      "privacy risk",
      "insurance paperwork",
      "care plan",
    ],
    triggerSeeds: [
      "missed appointment",
      "test result",
      "pharmacy receipt",
      "insurance notice",
      "family asking questions",
      "clinic waiting room",
      "healthcare bill",
      "private decision",
    ],
    compilerHints: [
      "Treat reproductive and healthcare stakes as opt-in trope pressure tied to agency, privacy, class, family, legal systems, and care.",
      "Where {{user}} is involved, keep decisions user-controlled and avoid automatic escalation.",
      "Use healthcare systems as consequence and access pressure, not melodrama alone.",
    ],
    antiPatterns: [
      "Do not introduce pregnancy or reproductive stakes unless explicitly selected, established, or strongly implied by the user or story setup.",
      "Do not use body-state stakes to override {{user}} agency.",
    ],
  },
  {
    slug: "objects_concepts_residue",
    label: "Objects, concepts, and residue",
    scope: ["world_book", "scenario_book", "memory_book", "character_book", "user_book"],
    fictionLabels: ["small things remember", "objects with history"],
    routeTags: [
      "object_residue",
      "concept_trigger",
      "emotional_anchor",
      "memory_residue",
    ],
    vocabularySeeds: [
      "borrowed jacket",
      "keycard",
      "shared playlist",
      "deleted text",
      "family rule",
      "public title",
      "private nickname",
      "seating arrangement",
      "locked drawer",
      "gift receipt",
      "spare key",
      "saved voicemail",
    ],
    triggerSeeds: [
      "wearing his jacket",
      "key still works",
      "song comes on",
      "message deleted",
      "nickname slips out",
      "gift returned",
      "drawer unlocked",
      "seat left empty",
    ],
    compilerHints: [
      "Use objects and concepts when they carry emotional history, forbidden desire, social risk, or behavioral triggers.",
      "Track objective reality separately from subjective meaning.",
      "Let small items become conversation triggers, vulnerability leaks, crossed lines, or memory anchors.",
    ],
    antiPatterns: [
      "Do not make every item symbolic.",
      "Do not keep meaningful objects from changing behavior, dialogue, or memory.",
    ],
  },
];

export function getContemporaryWorldVocabularySeed(
  slug: string,
): ContemporaryWorldVocabularySeed | undefined {
  return contemporaryWorldVocabularySeeds.find((seed) => seed.slug === slug);
}

export function findContemporaryWorldVocabularySeedsByTag(
  tag: string,
): ContemporaryWorldVocabularySeed[] {
  return contemporaryWorldVocabularySeeds.filter((seed) =>
    seed.routeTags.includes(tag),
  );
}
