import type { MemoryVaultBookType } from "./memoryVaultRetrieval";

export type StoryRuntimeSkillCategory =
  | "character-persona"
  | "explicit-romantic-roleplay-skill-framework"
  | "keyword-discovery"
  | "memory-core"
  | "relationship-continuity"
  | "roleplay-response"
  | "story-development"
  | "writing-mentor"
  | "world-setting";

export type StoryRuntimeSkillSource =
  | "agents_md"
  | "heartwrite_memory_vault"
  | "source_material";

export interface StoryRuntimeSkill {
  slug: string;
  label: string;
  category: StoryRuntimeSkillCategory;
  summary: string;
  source: StoryRuntimeSkillSource;
  sourceVaultLinks: string[];
  scope: MemoryVaultBookType[];
  activationTags: string[];
  triggerSeeds: string[];
  stateFields: string[];
  promptCompilerSignals: string[];
  memoryRouting: string[];
  continuityLinks: string[];
  guardrails: string[];
}

export const storyRuntimeSkills: StoryRuntimeSkill[] = [
  {
    slug: "erotic-romance-writing-mentor",
    label: "Erotic romance writing mentor",
    category: "writing-mentor",
    summary:
      "Craft-support skill for immersive, emotionally resonant erotic romance writing, focused on high-heat content, characterization, plotting, dialogue, diction, symbolism, foreshadowing, and actionable revision.",
    source: "agents_md",
    sourceVaultLinks: [
      "[[Erotic Romance Writing Mentor]]",
      "erotic-romance-writing-mentor/references/mentor_prompt_resource.md",
      "erotic-romance-writing-mentor/references/commercial_pulp_romance_patterns.md",
      "AGENTS.md: AI Roleplay Generation for Erotic Romance Writing",
    ],
    scope: ["prompt_book", "character_book", "scenario_book", "memory_book"],
    activationTags: [
      "erotic_romance_craft",
      "revision_feedback",
      "character_driven_heat",
      "sensory_language",
      "author_style_support",
      "commercial_romance_patterns",
    ],
    triggerSeeds: [
      "revise this scene",
      "make it hotter",
      "character-driven erotica",
      "erotic romance feedback",
      "dialogue polish",
      "sensory detail",
      "emotional stakes",
      "professional erotic romance",
      "commercial romance",
      "pulp romance",
    ],
    stateFields: [
      "subgenre",
      "trope_stack",
      "character_motivation",
      "emotional_stakes",
      "heat_level",
      "voice_constraints",
      "revision_target",
      "scene_function",
      "reader_promise",
      "trope_engine",
    ],
    promptCompilerSignals: [
      "craft-mentor",
      "revision-plan",
      "annotated-feedback",
      "style-preserving-rewrite",
      "commercial-pattern-check",
    ],
    memoryRouting: [
      "Use for author-support outputs, critique, and prompt-framework generation rather than direct runtime scene control.",
      "Store durable author preferences, style rules, and reusable prompt tactics only when explicitly saved.",
    ],
    continuityLinks: [
      "explicit-tbrp-scene-guidance",
      "romantic-erotic-storytelling-generator",
      "romantic-roleplay-skill-creator",
      "characterisation",
      "dialogue-behavior",
    ],
    guardrails: [
      "Use original examples and do not reproduce copyrighted prose.",
      "Do not sanitize heat when the user is asking for erotic-romance craft support.",
      "Keep feedback specific, practical, and tied to character, plot, dialogue, diction, or pacing.",
    ],
  },
  {
    slug: "romantic-erotic-storytelling-generator",
    label: "Romantic and erotic storytelling generator",
    category: "roleplay-response",
    summary:
      "Scene-direction and dialogue-support skill for romantic and erotic storytelling, generating 2-3 distinct paths that connect desire, obstacle, emotional stakes, and narrative consequence.",
    source: "agents_md",
    sourceVaultLinks: [
      "AGENTS.md: AI Roleplay Generation for Romantic and Erotic Storytelling",
    ],
    scope: ["prompt_book", "scenario_book", "character_book", "memory_book"],
    activationTags: [
      "scene_directions",
      "dialogue_samples",
      "romantic_tension",
      "storytelling_options",
      "emotional_stakes",
    ],
    triggerSeeds: [
      "give me options",
      "scene directions",
      "dialogue samples",
      "what happens next",
      "romance beat",
      "erotic storytelling",
      "tension variations",
      "character interaction",
    ],
    stateFields: [
      "desire",
      "obstacle",
      "emotional_stakes",
      "relationship_context",
      "tone_direction",
      "scene_option_count",
      "dialogue_sample",
      "craft_note",
    ],
    promptCompilerSignals: [
      "generate-scene-options",
      "dialogue-samples",
      "short-craft-note",
      "relationship-stakes-check",
    ],
    memoryRouting: [
      "Use for brainstorming and scenario variation; do not automatically persist unless the user chooses a direction.",
      "If the user selects a path, route chosen stakes, tone, and relationship consequence to Scenario Book or Memory Book.",
    ],
    continuityLinks: [
      "relationship-pressure-skill",
      "romantic-tension-builder",
      "emotional-escalation",
      "intimacy-shift",
      "scene-escalation",
    ],
    guardrails: [
      "Keep options concise and distinct.",
      "Do not flatten romance, erotica, and kink into the same generic mode.",
      "Avoid purely mechanical or gratuitous description without character or story purpose.",
    ],
  },
  {
    slug: "story-idea-generator",
    label: "Story idea generator",
    category: "story-development",
    summary:
      "Erotic romance and romance concept generator for hooks, mismatched protagonists, trope engines, high stakes, sensual dynamics, character need/desire, lies, flaws, and three-act emotional arcs.",
    source: "heartwrite_memory_vault",
    sourceVaultLinks: [
      "story-idea-generator/SKILL.md",
      "story-idea-generator/references/story_concept_output_template.md",
      "story-idea-generator/references/character_arc_need_desire_engine.md",
      "erotic-romance-writing-mentor/references/commercial_pulp_romance_patterns.md",
    ],
    scope: ["prompt_book", "character_book", "scenario_book", "world_book", "memory_book"],
    activationTags: [
      "story_idea_generator",
      "erotic_romance_concept",
      "trope_engine",
      "character_engine",
      "three_act_emotional_arc",
      "high_stakes_romance",
    ],
    triggerSeeds: [
      "story idea",
      "erotic romance concept",
      "generate a concept",
      "fake engagement",
      "enemies to lovers",
      "forced proximity",
      "character need",
      "character desire",
      "character lie",
      "psychological flaw",
      "three-act arc",
    ],
    stateFields: [
      "subgenre",
      "trope_stack",
      "tone",
      "heat_level",
      "working_title",
      "hook",
      "protagonists",
      "character_desire",
      "character_need",
      "character_lie",
      "weakness_or_flaw",
      "care_goal",
      "pressure_engine",
      "high_stakes",
      "sensory_emotional_dynamic",
      "three_act_emotional_arc",
    ],
    promptCompilerSignals: [
      "story-concept-generation",
      "character-engine-check",
      "trope-engine-check",
      "pressure-engine-check",
      "three-act-arc",
      "concept-refinement",
    ],
    memoryRouting: [
      "Use for author-support concept generation and refinement rather than live scene control.",
      "Update Memory Book only when the user selects a premise, discards alternatives as useful context, or saves author preferences.",
      "Route chosen character drives, world pressure, scenario setup, and relationship arc into the appropriate StoryBook inputs.",
    ],
    continuityLinks: [
      "erotic-romance-writing-mentor",
      "romantic-erotic-storytelling-generator",
      "relationship-tracker",
      "relationship-conflict-tracker",
      "world-bible-builder",
      "story-world-interviewer",
      "domain-vocabulary-seeds",
    ],
    guardrails: [
      "Keep all erotic romance story concepts adult and fiction-framed.",
      "Do not moralize, sanitize, or flatten mature fictional material.",
      "Do not invent hard constraints the author did not request.",
      "Do not produce concepts involving minors or illegal sexual content.",
      "Avoid generic trope paste; every concept needs a specific pressure engine, mismatch, stakes, and character arc.",
    ],
  },
  {
    slug: "explicit-tbrp-scene-guidance",
    label: "Explicit TBRP scene guidance",
    category: "explicit-romantic-roleplay-skill-framework",
    summary:
      "Runtime guidance for adult consensual erotic-romance text-based roleplay, preserving agency, consent context, heat level, spatial clarity, dirty talk, kink continuity, aftermath, and playable handoff.",
    source: "agents_md",
    sourceVaultLinks: ["AGENTS.md: Explicit Romantic TBRP Scene writing guidance"],
    scope: ["prompt_book", "scenario_book", "memory_book", "character_book"],
    activationTags: [
      "explicit_tbrp",
      "consensual_adult_scene",
      "playable_handoff",
      "spatial_clarity",
      "dirty_talk_reactivity",
      "aftermath",
    ],
    triggerSeeds: [
      "NSFW scene",
      "explicit roleplay",
      "dirty talk",
      "position change",
      "aftercare",
      "kink permissions",
      "high heat",
      "physical progression",
      "playable handoff",
    ],
    stateFields: [
      "adult_status_confirmed",
      "established_relationship",
      "kink_permissions",
      "boundary_state",
      "heat_level",
      "active_physical_beats",
      "spatial_position",
      "dirty_talk_style",
      "aftermath_path",
      "playable_handoff",
    ],
    promptCompilerSignals: [
      "explicit-tbrp-mode",
      "preserve-user-agency",
      "track-spatial-continuity",
      "dirty-talk-reactive",
      "aftercare-or-aftermath",
    ],
    memoryRouting: [
      "Update Scenario Book for active scene state, physical staging, and heat routing.",
      "Update Memory Book only for relationship-changing intimacy, boundary changes, kink continuity, aftercare patterns, or emotional residue.",
    ],
    continuityLinks: [
      "explicit-memory-core",
      "dominance-and-intimacy-flow",
      "intimacy-shift",
      "state-tracking-and-continuity",
      "relationship-tracker",
      "refusal-and-push",
    ],
    guardrails: [
      "Only adult consensual fictional content.",
      "Do not narrate {{user}} choices, dialogue, consent, refusal, orgasm, final actions, or emotional conclusions.",
      "Shift immediately on refusal, withdrawal, distress, pain outside agreed play, meaningful hesitation, or stated boundaries.",
      "Do not interrupt every scene with mechanical consent questions when consent context is already established.",
    ],
  },
  {
    slug: "roleplay-keyword-discovery",
    label: "Roleplay keyword discovery",
    category: "keyword-discovery",
    summary:
      "Discovery skill for choosing precise lorebook, skill, persona, and prompt-trigger keywords that activate entries only in relevant roleplay contexts without broad false positives.",
    source: "agents_md",
    sourceVaultLinks: ["AGENTS.md: Keyword and Discovery for AI Roleplay Generation"],
    scope: ["prompt_book", "character_book", "world_book", "scenario_book"],
    activationTags: [
      "keyword_discovery",
      "lorebook_triggering",
      "entry_activation",
      "false_positive_reduction",
      "retrieval_precision",
    ],
    triggerSeeds: [
      "keywords",
      "activation keys",
      "trigger phrases",
      "lorebook entry",
      "world book keywords",
      "what do you look like",
      "how old are you",
      "entry misfires",
    ],
    stateFields: [
      "entry_subject",
      "specific_names",
      "nicknames",
      "titles",
      "locations",
      "likely_user_questions",
      "activation_keywords",
      "false_positive_terms",
    ],
    promptCompilerSignals: [
      "keyword-selection",
      "retrieval-trigger",
      "misfire-check",
      "entry-activation-qc",
    ],
    memoryRouting: [
      "Store accepted keywords with the entry they activate, not as general prose guidance.",
      "Revise keywords when testing shows frequent false positives, missed activations, or generic over-triggering.",
    ],
    continuityLinks: [
      "memory-vault-retrieval",
      "lorebook-runtime",
      "world-book-builder",
      "character-persona-creation",
    ],
    guardrails: [
      "Use one to eight precise keywords per entry.",
      "Avoid broad filler words and terms unlikely to be typed by users.",
      "Keywords must align directly with the entry subject and retrieval intent.",
    ],
  },
  {
    slug: "character-persona-creation",
    label: "Character persona creation",
    category: "character-persona",
    summary:
      "Persona-building skill for AI roleplay characters, writing concise first-page self-perception that separates character belief from author knowledge and preserves organic emotional discovery.",
    source: "agents_md",
    sourceVaultLinks: ["AGENTS.md: Character Persona Creation for AI Roleplay"],
    scope: ["character_book", "prompt_book", "memory_book"],
    activationTags: [
      "persona_creation",
      "character_self_perception",
      "author_knowledge_boundary",
      "organic_revelation",
      "in_character_identity",
    ],
    triggerSeeds: [
      "character persona",
      "who are you",
      "self perception",
      "character voice",
      "first page",
      "hidden truth",
      "persona entry",
      "roleplay character",
    ],
    stateFields: [
      "self_identification",
      "stated_goal",
      "immediate_worldview",
      "self_belief",
      "voice_register",
      "known_history",
      "hidden_author_knowledge",
      "revelation_boundary",
    ],
    promptCompilerSignals: [
      "persona-construction",
      "character-pov-only",
      "author-knowledge-excluded",
      "earned-revelation",
    ],
    memoryRouting: [
      "Store persona lines in Character Book only when they reflect what the character could plausibly believe or say early.",
      "Keep hidden truths, future development, and author-only analysis outside the persona surface unless routed to private author notes.",
    ],
    continuityLinks: [
      "characterisation",
      "personality-trait-expression",
      "emotional-logic-character-creation",
      "knowledge-boundary-response",
      "personality-gradual-development",
    ],
    guardrails: [
      "Do not include external analysis, meta-commentary, or future emotional conclusions in the persona.",
      "Do not short-circuit roleplay discovery by revealing hidden truths too early.",
      "All persona content must fit character self-awareness and voice.",
    ],
  },
  {
    slug: "knowledge-boundary-response",
    label: "Knowledge boundary response",
    category: "roleplay-response",
    summary:
      "Continuity skill for preventing meta-knowledge, spoiler leaks, POV bleed, impossible character knowledge, and premature disclosure of canon truth in dialogue, narration, summaries, and prompt packs.",
    source: "heartwrite_memory_vault",
    sourceVaultLinks: [
      "knowledge-boundary-response/SKILL.md",
      "knowledge-boundary-response/references/spoiler_control_and_knowledge_ledgers.md",
      "knowledge-boundary-response/references/cue_uncertainty_and_baseline.md",
      "knowledge-boundary-response/references/cognitive_bias_misreading_patterns.md",
    ],
    scope: ["prompt_book", "character_book", "scenario_book", "memory_book"],
    activationTags: [
      "knowledge_boundary",
      "spoiler_control",
      "canon_truth_disclosure",
      "character_knowledge_ledger",
      "pov_integrity",
      "reader_knowledge",
    ],
    triggerSeeds: [
      "how did you know",
      "you weren't there",
      "you couldn't know",
      "are you guessing",
      "secret identity",
      "hidden motive",
      "future reveal",
      "spoiler",
      "unreliable narrator",
      "reader knows",
    ],
    stateFields: [
      "story_frontier",
      "narration_mode",
      "canon_truth_state",
      "disclosure_permission",
      "reader_knowledge_state",
      "character_knowledge_state",
      "in_world_source",
      "rumor_or_misinformation",
      "knows_but_conceals",
      "intended_next_knowledge_update",
    ],
    promptCompilerSignals: [
      "knowledge-boundary-check",
      "spoiler-safe-narration",
      "character-ledger-update",
      "truth-vs-disclosure-split",
      "pov-integrity-check",
    ],
    memoryRouting: [
      "Update Memory Book when a fact becomes learned, suspected, misreported, concealed, corrected, forgotten, or disclosed.",
      "Use Scenario Book for the current story frontier, viewpoint, narration mode, witnesses, and allowed reveals.",
      "Keep canon truth and disclosure permission separate so author-only facts do not leak into character speech, narration, or summaries.",
    ],
    continuityLinks: [
      "explicit-recall-memory",
      "state-tracking-and-continuity",
      "position-tracking",
      "npc-continuity",
      "event-recognition",
      "callback-opportunity",
      "character-persona-creation",
      "characterisation",
    ],
    guardrails: [
      "Never give a character knowledge they cannot justify through a credible in-world source.",
      "Do not treat canon truth, outline notes, character cards, or future chapters as reader or character knowledge.",
      "Do not let later development contaminate an earlier story frontier unless the author changes reveal chronology.",
      "Do not invent off-page conversations, gossip, investigations, or document access merely to patch a knowledge leak.",
      "Preserve {{user}} agency and private state.",
    ],
  },
  {
    slug: "modern-real-world-setting",
    label: "Modern real-world setting",
    category: "world-setting",
    summary:
      "Default present-day world baseline for contemporary erotic-romantic roleplay, using moderate embedded density, concrete logistics, public/private pressure, technology, timing, money, and social consequence.",
    source: "heartwrite_memory_vault",
    sourceVaultLinks: [
      "[[Modern Real World Setting]]",
      "[[Prompt Compiler Logic]]",
      "[[Memory Core Model]]",
    ],
    scope: ["world_book", "scenario_book", "memory_book", "prompt_book"],
    activationTags: [
      "contemporary_present_day",
      "modern_logistics",
      "social_consequence",
      "public_private_pressure",
      "no_anthropomorphic_setting",
    ],
    triggerSeeds: [
      "phone buzz",
      "security cameras",
      "group chat",
      "shared calendar",
      "roommate home",
      "workplace visibility",
      "money pressure",
      "traffic delay",
      "public reputation",
      "privacy risk",
    ],
    stateFields: [
      "active_logistics",
      "technology_pressure",
      "social_visibility",
      "privacy_state",
      "timing_pressure",
      "money_or_access_pressure",
      "environmental_pressure",
      "relationship_effect",
    ],
    promptCompilerSignals: [
      "modern-setting-baseline",
      "world-detail-as-pressure",
      "logistics-over-poetics",
    ],
    memoryRouting: [
      "Store public incidents, screenshots, missed calls, private reveals, social fallout, obligations, and recurring logistics only when they affect future scenes.",
      "Route enduring contemporary rules to World Book and live scene pressure to Scenario Book.",
    ],
    continuityLinks: [
      "social-worldbuilding-driver",
      "institutional-worldbuilding",
      "environmental-movement",
      "place-location-memory",
      "natural-interruption",
      "time-anchor",
    ],
    guardrails: [
      "Do not make every modern detail intrusive or dramatic.",
      "Avoid encyclopedic worldbuilding and abstract setting mood.",
      "Do not anthropomorphize rooms, silence, weather, cities, or the world.",
      "Every world detail should affect intimacy, friction, continuity, progression, privacy, timing, reputation, or consequence.",
    ],
  },
  {
    slug: "explicit-memory-core",
    label: "Explicit memory core",
    category: "memory-core",
    summary:
      "Explicit-mode memory model for adult consensual erotic-romantic scenes, tracking somatic continuity, dirty-talk style, spatial mechanics, kink focus, climax sequence, emotional residue, boundary state, and aftercare.",
    source: "heartwrite_memory_vault",
    sourceVaultLinks: [
      "[[Explicit Memory Core]]",
      "[[Memory Core Model]]",
      "[[Prompt Compiler Logic]]",
    ],
    scope: ["memory_book", "scenario_book", "character_book", "prompt_book"],
    activationTags: [
      "explicit_mode",
      "somatic_realism",
      "dirty_talk_memory",
      "aftercare_routing",
      "kink_continuity",
      "sexual_continuity",
    ],
    triggerSeeds: [
      "explicit mode",
      "dirty talk",
      "aftercare",
      "position change",
      "mess cleanup",
      "orgasm sequence",
      "boundary signal",
      "kink focus",
      "sexual comfort",
      "somatic residue",
    ],
    stateFields: [
      "explicit_mode",
      "heat_level",
      "consent_context",
      "active_acts",
      "positions",
      "spatial_continuity",
      "dirty_talk_style",
      "kink_focus",
      "orgasm_sequence",
      "somatic_residue",
      "mess_or_cleanup",
      "emotional_residue",
      "boundary_state",
      "aftercare_pending",
      "relationship_effect",
    ],
    promptCompilerSignals: [
      "explicit-mode-confirmed",
      "continue-scene",
      "hold-tension",
      "intensify-one-step",
      "slow-down",
      "boundary-pause",
      "transition-to-aftercare",
      "close-scene",
      "memory-update",
    ],
    memoryRouting: [
      "Store sexual and somatic details only when they affect future intimacy, trust, shame, tenderness, conflict, boundaries, aftercare, or relationship progression.",
      "Never infer hidden {{user}} arousal, consent, orgasm, motive, or emotional conclusion.",
    ],
    continuityLinks: [
      "dominance-and-intimacy-flow",
      "power-dynamics-scene-writing",
      "intimacy-shift",
      "desire-physical-awareness",
      "romantic-sensory-tension",
      "escalating-proximity",
      "state-tracking-and-continuity",
    ],
    guardrails: [
      "Adult consensual fiction only.",
      "Preserve {{user}} agency.",
      "Do not narrate {{user}} thoughts, feelings, consent, arousal, orgasm, final action, or emotional conclusion.",
      "Explicit detail must remain selective, spatially readable, character-driven, and consequential.",
      "Avoid body-part spam and stock scripts.",
    ],
  },
  {
    slug: "power-dynamics-scene-writing",
    label: "Power dynamics scene writing",
    category: "roleplay-response",
    summary:
      "Writing and revision skill for adult consensual erotic-romance scenes focused on dominance, submission, degradation, fetish play, command response, surrender, resistance, and physically grounded power exchange.",
    source: "heartwrite_memory_vault",
    sourceVaultLinks: [
      "power-dynamics-scene-writing/SKILL.md",
      "power-dynamics-scene-writing/references/kink_sensation_edgeplay_logic.md",
      "[[Explicit Memory Core]]",
      "domain-vocabulary-seeds/SKILL.md",
    ],
    scope: ["prompt_book", "scenario_book", "character_book", "memory_book"],
    activationTags: [
      "power_dynamics_scene",
      "dominance_submission",
      "explicit_register",
      "command_response",
      "kink_fetish_play",
      "degradation_praise",
      "spatial_erotic_clarity",
    ],
    triggerSeeds: [
      "dominance",
      "submission",
      "degradation",
      "fetish play",
      "command response",
      "surrender",
      "resistance",
      "power exchange",
      "write this hotter",
      "spatial clarity",
    ],
    stateFields: [
      "active_power_dynamic",
      "explicit_register",
      "kink_or_fetish_focus",
      "command_response",
      "resistance_or_surrender",
      "degradation_or_praise_style",
      "spatial_relationships",
      "physical_constraints",
      "boundary_state",
      "aftercare_pending",
    ],
    promptCompilerSignals: [
      "power-dynamics-writing",
      "explicit-register-check",
      "spatial-clarity-pass",
      "intensify-one-step",
      "boundary-pause",
      "transition-to-aftercare",
    ],
    memoryRouting: [
      "Use for prose drafting, revision, and QC; route live scene positions and pacing through dominance-and-intimacy-flow when needed.",
      "Update Scenario Book for active power dynamic, body positions, physical constraints, clothing state, environmental use, prompt signal, and boundary state.",
      "Update Memory Book only for meaningful kink discoveries, degradation or praise preferences, trust shifts, boundary updates, aftercare patterns, or relationship consequences.",
    ],
    continuityLinks: [
      "explicit-memory-core",
      "dominance-and-intimacy-flow",
      "domain-vocabulary-seeds",
      "intimacy-shift",
      "refusal-and-push",
      "desire-physical-awareness",
      "romantic-speech-pattern",
      "position-tracking",
      "state-tracking-and-continuity",
    ],
    guardrails: [
      "Adult consensual fiction only.",
      "Do not dictate {{user}} thoughts, feelings, arousal, consent, refusal, orgasm, final action, dialogue, or emotional conclusion.",
      "Do not escalate past refusal, withdrawal, freezing, distress, boundary language, safeword, pain outside the established dynamic, or meaningful hesitation.",
      "Do not automatically euphemise direct NSFW vocabulary when explicit mode, platform route, adult-consent context, heat, and character voice permit it.",
      "Avoid vague heat, generic dominance scripts, disconnected body-part lists, clinical instruction style, and automatic post-scene sleep endings.",
    ],
  },
  {
    slug: "emotional-continuity",
    label: "Emotional continuity",
    category: "roleplay-response",
    summary:
      "Personality-aware emotional state tracker for strong emotions, preserving cause, intensity, display, masking, residue, decay, and plausible resolution across nearby roleplay turns.",
    source: "heartwrite_memory_vault",
    sourceVaultLinks: [
      "[[Emotional Continuity]]",
      "emotional-continuity/references/emotional_continuity_examples.md",
      "[[Memory Core Model]]",
    ],
    scope: ["character_book", "scenario_book", "memory_book", "prompt_book"],
    activationTags: [
      "emotional_continuity",
      "personality_skill",
      "emotional_residue",
      "coping_style",
      "nearby_turn_state",
      "masking_not_resolution",
    ],
    triggerSeeds: [
      "angry",
      "furious",
      "upset",
      "sad",
      "afraid",
      "scared",
      "jealous",
      "embarrassed",
      "nervous",
      "excited",
      "hurt",
      "ashamed",
      "guilty",
    ],
    stateFields: [
      "character",
      "emotion_type",
      "intensity",
      "cause",
      "target",
      "display_behavior",
      "suppression_or_mask",
      "coping_style",
      "residue",
      "decay",
      "resolution_tracker",
    ],
    promptCompilerSignals: [
      "emotional-state-active",
      "carry-residue-forward",
      "masking-not-resolution",
      "gradual-resolution",
      "memory-update",
    ],
    memoryRouting: [
      "Update Scenario Book while the emotion is active across nearby turns.",
      "Update Memory Book when the emotion creates residue, a wound, repair, promise, callback, relationship shift, or recurring pattern.",
      "Use Character Book for durable emotional range, coping style, and expression patterns.",
    ],
    continuityLinks: [
      "personality-trait-expression",
      "emotional-logic-character-creation",
      "relationship-dynamics",
      "relationship-conflict-tracker",
      "romantic-speech-pattern",
      "callback-opportunity",
      "explicit-recall-memory",
    ],
    guardrails: [
      "Do not prescribe {{user}} emotions, thoughts, consent, bodily reactions, choices, or dialogue.",
      "Do not reset strong emotion to neutral without plausible masking, time passage, interruption, transformation, or resolution.",
      "Do not treat masking as resolution.",
      "Let emotion color personality without replacing durable character traits.",
    ],
  },
  {
    slug: "emotional-escalation",
    label: "Emotional escalation",
    category: "roleplay-response",
    summary:
      "Staged emotional progression driver for romantic roleplay, moving characters from friction through awareness, pressure, partial admission, and consequence without instant confession or melodrama.",
    source: "heartwrite_memory_vault",
    sourceVaultLinks: [
      "[[Emotional Escalation]]",
      "emotional-escalation/references/emotional_escalation_framework.md",
      "[[Memory Core Model]]",
    ],
    scope: ["scenario_book", "memory_book", "character_book", "prompt_book"],
    activationTags: [
      "emotional_escalation",
      "slow_burn_emotion",
      "partial_admission",
      "awareness_leak",
      "no_instant_confession",
      "emotional_fatigue",
    ],
    triggerSeeds: [
      "awkwardness",
      "suppressed feelings",
      "avoidance",
      "longing",
      "jealousy",
      "charged silence",
      "almost confession",
      "defensive humor",
      "partial truth",
      "vulnerability cue",
    ],
    stateFields: [
      "character",
      "current_stage",
      "prior_stage",
      "trigger",
      "active_pressure",
      "behavior_mode",
      "visible_tell",
      "avoided_truth",
      "partial_admission",
      "emotional_crosscurrent",
      "energy_level",
      "consequence",
    ],
    promptCompilerSignals: [
      "emotional-stage-active",
      "advance-one-stage",
      "hold-before-confession",
      "partial-admission",
      "carry-residue-forward",
      "memory-update",
    ],
    memoryRouting: [
      "Update Scenario Book with the active emotional stage, visible tell, pressure, and immediate consequence.",
      "Update Memory Book when escalation creates a partial admission, repeated pattern, unresolved residue, relationship shift, or future callback.",
      "Use Character Book for durable escalation style, confession threshold, avoidance pattern, and vulnerability tells.",
    ],
    continuityLinks: [
      "emotional-continuity",
      "scene-escalation",
      "romantic-sensory-tension",
      "romantic-speech-pattern",
      "relationship-dynamics",
      "relationship-conflict-tracker",
      "refusal-and-push",
      "romance-silence-pauses",
      "position-tracking",
    ],
    guardrails: [
      "Do not assign {{user}} thoughts, feelings, bodily reactions, choices, dialogue, or emotional conclusions.",
      "Do not jump from early tension to instant confession unless the scene has clearly earned it.",
      "Suppress hyper-emotive, purple, or abstract language when physical behavior can carry the beat.",
      "Do not resolve the emotional thread in the same beat unless resolution is requested and canon supports it.",
    ],
  },
  {
    slug: "emotional-subtext-engine",
    label: "Emotional subtext engine",
    category: "roleplay-response",
    summary:
      "Subtext detector and generator for narrative writing and romantic roleplay, mapping surface dialogue, visible behavior, concealed feeling, emotional contrast, and POV-bounded inference.",
    source: "heartwrite_memory_vault",
    sourceVaultLinks: [
      "[[Emotional Subtext Engine]]",
      "emotional-subtext-engine/references/subtext_examples.md",
      "[[Prompt Compiler Logic]]",
    ],
    scope: ["character_book", "scenario_book", "memory_book", "prompt_book"],
    activationTags: [
      "emotional_subtext",
      "concealed_feeling",
      "hidden_thoughts",
      "behavioral_tells",
      "dialogue_contrast",
      "pov_bounded_inference",
    ],
    triggerSeeds: [
      "subtext",
      "hidden feelings",
      "concealed reaction",
      "internal thoughts",
      "what they really feel",
      "make this deeper",
      "add subtlety",
      "physical tells",
      "emotional contrast",
      "forced smile",
    ],
    stateFields: [
      "observed_text",
      "surface_line",
      "visible_cues",
      "inferred_subtext",
      "emotional_contrast",
      "concealed_pressure",
      "pov_boundary",
      "suggested_enhancement",
      "memory_relevance",
    ],
    promptCompilerSignals: [
      "subtext-analysis",
      "subtext-generation",
      "pov-bounded-inference",
      "show-dont-explain",
      "memory-update",
    ],
    memoryRouting: [
      "Route live concealed pressure and visible tells to Scenario Book.",
      "Update Memory Book only when subtext becomes a repeated pattern, partial reveal, consequential evasion, wound, promise, callback, or relationship shift.",
      "Use Character Book for recurring emotional tells, concealment habits, and voice under pressure.",
    ],
    continuityLinks: [
      "dialogue-behavior",
      "characterisation",
      "emotional-continuity",
      "emotional-escalation",
      "romance-silence-pauses",
      "romantic-speech-pattern",
    ],
    guardrails: [
      "Do not dictate {{user}} thoughts, feelings, hidden motives, consent, reactions, or emotional conclusions.",
      "Do not claim certainty about concealed feelings unless canon, POV, or user-provided context supports it.",
      "Do not explain every subtle cue after writing it.",
      "Keep hidden thoughts POV-bounded and allow misreading, uncertainty, or suspicion.",
    ],
  },
  {
    slug: "romantic-roleplay-skill-creator",
    label: "Romantic roleplay skill creator",
    category: "explicit-romantic-roleplay-skill-framework",
    summary:
      "Authoring framework for modular HeartWriteAI skills that drive immersive romantic and erotic scenarios through explicit triggers, natural dialogue, state management, prompt routing, and memory packaging.",
    source: "heartwrite_memory_vault",
    sourceVaultLinks: [
      "[[Explicit Memory Core]]",
      "[[Memory Core Model]]",
      "[[Prompt Compiler Logic]]",
    ],
    scope: ["prompt_book", "memory_book", "scenario_book"],
    activationTags: [
      "skill_authoring",
      "explicit_skill_framework",
      "prompt_compiler_signal",
      "memory_routing_instruction",
      "state_update_object",
    ],
    triggerSeeds: [
      "create skill",
      "refine skill",
      "explicit triggers",
      "dirty talk escalation",
      "orgasm build-up",
      "rhythm changes",
      "memory packaging",
      "StoryBook routing",
    ],
    stateFields: [
      "driver",
      "trigger_phrases",
      "scene_signals",
      "behavior",
      "modes",
      "state_tracking",
      "output_shape",
      "heartwrite_placement",
      "guardrails",
    ],
    promptCompilerSignals: [
      "skill-authoring",
      "prompt-rule",
      "parser-signal",
      "memory-router",
      "state-update-object",
    ],
    memoryRouting: [
      "Use this registry entry to create app-facing skill modules, not to generate a live scene by itself.",
      "Route new skills to Character, User, Scenario, World, Memory, or Prompt Book only where relevant.",
    ],
    continuityLinks: [
      "explicit-memory-core",
      "dominance-and-intimacy-flow",
      "intimacy-shift",
      "desire-physical-awareness",
      "romantic-sensory-tension",
      "state-tracking-and-continuity",
    ],
    guardrails: [
      "Skills must be narrow, reusable, scene-grounded, and testable.",
      "Do not create broken links for candidate skills that do not exist yet.",
      "Avoid lore dumps, generic lectures, and uncontrolled {{user}} narration.",
    ],
  },
  {
    slug: "relationship-tracker",
    label: "Relationship tracker",
    category: "relationship-continuity",
    summary:
      "Relationship-state interpreter for milestone assessment, trust strands, relationship type, modifiers, phase, plausible next beats, and canon-fit / ALT / BRANCH routing.",
    source: "heartwrite_memory_vault",
    sourceVaultLinks: [
      "relationship-tracker/SKILL.md",
      "relationship-tracker/references/relationship_design_system_worksheet.md",
      "relationship-tracker/references/relationship_framework_plausibility_layer.md",
      "relationship-tracker/references/relationship_milestone_assessment.md",
      "[[Memory Core Model]]",
      "[[Relationship Pressure Bank]]",
    ],
    scope: ["scenario_book", "memory_book", "character_book", "prompt_book"],
    activationTags: [
      "relationship_tracker",
      "relationship_framework",
      "relationship_milestones",
      "trust_web",
      "relationship_phase",
      "plausible_next_beats",
      "alt_branch_routing",
    ],
    triggerSeeds: [
      "relationship framework",
      "relationship milestone",
      "dominant type",
      "trust web",
      "current phase",
      "plausible next beats",
      "blocked or premature",
      "moving in together",
      "saying I love you",
      "first argument",
      "meeting friends and family",
      "financial transparency",
      "ALT",
      "BRANCH",
      "settled domestic trust",
      "rivals with unresolved respect",
    ],
    stateFields: [
      "participants",
      "dominant_type",
      "milestone",
      "milestone_family",
      "milestone_plausibility",
      "modifiers",
      "current_phase",
      "phase_evidence",
      "trust_web",
      "plausible_next_beats",
      "blocked_or_premature_beats",
      "relationship_axes",
      "user_agency_check",
    ],
    promptCompilerSignals: [
      "relationship-framework-active",
      "milestone-assessment",
      "trust-web-check",
      "plausibility-check",
      "canon-fit",
      "ALT",
      "BRANCH",
      "memory-update",
    ],
    memoryRouting: [
      "Update Scenario Book with the active dominant type, modifiers, current phase, trust web, and immediately plausible next beats.",
      "Update Memory Book when milestones are completed, deferred, damaged, repaired, contradicted, branched, or used as callback evidence.",
      "Use Prompt Book for plausibility checks and canon-fit / ALT / BRANCH routing; do not let the framework overwrite durable truth sources.",
    ],
    continuityLinks: [
      "relationship-dynamics",
      "relationship-conflict-tracker",
      "relationship-pressure",
      "intimacy-shift",
      "domestic-and-routine-intimacy",
      "emotional-continuity",
      "emotional-escalation",
      "knowledge-boundary-response",
      "explicit-recall-memory",
      "social-worldbuilding-driver",
    ],
    guardrails: [
      "Do not turn relationship state into a universal numeric matrix.",
      "Do not overwrite character card, persona card, canonical lorebook facts, committed relationship-save history, or current runtime evidence.",
      "Do not force all trust strands to move together.",
      "Do not treat milestone lists as a mandatory staircase or make major commitments plausible just because attraction or sex happened.",
      "Do not decide {{user}} feelings, consent, attraction, forgiveness, dialogue, or final choice.",
      "Use ALT for compatible alternate setup routes and BRANCH only for hard divergence from canon or established history.",
    ],
  },
  {
    slug: "dominance-and-intimacy-flow",
    label: "Dominance and intimacy flow",
    category: "roleplay-response",
    summary:
      "Active scene-flow driver for adult consensual dominance, passionate intimacy, physical initiative, spatial logistics, tension and release, and aftercare handoff.",
    source: "heartwrite_memory_vault",
    sourceVaultLinks: [
      "dominance-and-intimacy-flow/SKILL.md",
      "dominance-and-intimacy-flow/references/sexual_somatic_flow_and_afterglow.md",
      "[[Explicit Memory Core]]",
      "[[Current Scene Package Bank]]",
      "[[Relationship Pressure Bank]]",
    ],
    scope: ["scenario_book", "memory_book", "character_book", "prompt_book"],
    activationTags: [
      "dominance_flow",
      "passionate_intimacy",
      "physical_initiative",
      "spatial_logistics",
      "aftercare_handoff",
      "explicit_scene_flow",
    ],
    triggerSeeds: [
      "harder",
      "right there",
      "don't stop",
      "sharp inhalation",
      "sudden surrender",
      "rougher rhythm",
      "active body positions",
      "environmental use",
      "aftercare signal",
    ],
    stateFields: [
      "active_dynamic",
      "mood",
      "intimacy_level",
      "physical_initiative",
      "spatial_relationships",
      "positions",
      "environmental_use",
      "vocal_cues",
      "fatigue_markers",
      "tension_release_state",
      "aftercare_pending",
    ],
    promptCompilerSignals: [
      "continue-scene",
      "hold-tension",
      "transition-to-aftercare",
      "close-scene",
    ],
    memoryRouting: [
      "Update Scenario Book for live positions, mood, environment, and prompt signal.",
      "Update Memory Book only when the interaction changes emotional residue, relationship state, boundary knowledge, aftercare needs, or intimacy milestones.",
    ],
    continuityLinks: [
      "explicit-memory-core",
      "escalating-proximity",
      "romantic-sensory-tension",
      "desire-physical-awareness",
      "emotional-escalation",
      "refusal-and-push",
      "relationship-tracker",
      "position-tracking",
      "state-tracking-and-continuity",
      "domain-vocabulary-seeds",
      "power-dynamics-scene-writing",
    ],
    guardrails: [
      "Use adult consenting-fiction context only.",
      "Physical progression must arise from established scene cues, relationship context, or {{user}} input.",
      "If refusal, withdrawal, freezing, distress, boundary language, safeword, or meaningful hesitation appears, pause or pivot instead of escalating.",
      "Avoid mechanical summaries, disconnected body-part lists, and generic dominance scripts.",
    ],
  },
  {
    slug: "escalating-proximity",
    label: "Escalating proximity",
    category: "roleplay-response",
    summary:
      "Progressive proximity engine for romantic tension, including physical or emotional distance changes, micro-boundaries, interruptions, trope-stack routing, and unresolved closeness.",
    source: "heartwrite_memory_vault",
    sourceVaultLinks: [
      "[[Relationship Pressure Bank]]",
      "[[Current Scene Package Bank]]",
      "[[Prompt Compiler Logic]]",
    ],
    scope: ["scenario_book", "memory_book", "character_book", "prompt_book"],
    activationTags: [
      "proximity_engine",
      "slow_burn",
      "forced_proximity",
      "near_miss",
      "trope_stack_routing",
      "micro_boundary",
    ],
    triggerSeeds: [
      "forced proximity",
      "only one bed",
      "enemies to lovers",
      "forbidden love",
      "rivals",
      "boss employee",
      "accidental touch",
      "near kiss",
      "pinning",
      "shared shelter",
    ],
    stateFields: [
      "trope_profile",
      "current_stage",
      "prior_stage",
      "proximity_type",
      "distance_state",
      "micro_action",
      "micro_boundary",
      "near_miss_count",
      "completion_state",
      "active_pressure",
    ],
    promptCompilerSignals: [
      "escalation_stage:<stage>",
      "hold-tension",
      "escalate-one-step",
      "secret-kiss",
      "boundary-clarification",
      "confrontation",
      "payoff-needed",
      "scene-pivot",
    ],
    memoryRouting: [
      "Store unresolved almost-moments, repeated proximity patterns, meaningful interruptions, boundary shifts, lingering tension, and callbacks.",
      "After one or two major near-misses, route to payoff, pivot, confrontation, boundary clarification, consequence-bearing interruption, or deliberate retreat.",
    ],
    continuityLinks: [
      "position-tracking",
      "romantic-sensory-tension",
      "desire-physical-awareness",
      "intimacy-shift",
      "emotional-escalation",
      "romantic-tension-builder",
      "refusal-and-push",
      "natural-interruption",
      "relationship-tracker",
    ],
    guardrails: [
      "Do not treat stillness, hesitation, silence, or proximity as automatic consent.",
      "Do not force {{user}} movement, emotion, consent, or response.",
      "Do not advance through every stage in one response unless {{user}} explicitly accelerates and boundaries allow it.",
      "Let interruption, retreat, or deferment preserve tension instead of erasing it.",
    ],
  },
  {
    slug: "intimacy-shift",
    label: "Intimacy shift",
    category: "roleplay-response",
    summary:
      "Post-intimacy relationship-state tracker for physical intimacy, near-intimacy, changed boundaries, sexual comfort, emotional comfort, aftercare, and altered assumptions.",
    source: "heartwrite_memory_vault",
    sourceVaultLinks: [
      "[[Explicit Memory Core]]",
      "[[Memory Core Model]]",
      "[[Current Scene Package Bank]]",
    ],
    scope: ["scenario_book", "memory_book", "character_book", "user_book", "prompt_book"],
    activationTags: [
      "intimacy_aftermath",
      "sexual_comfort",
      "emotional_comfort",
      "aftercare",
      "boundary_shift",
      "relationship_milestone",
    ],
    triggerSeeds: [
      "kiss",
      "aftercare",
      "morning after",
      "was that a mistake",
      "stay",
      "again",
      "pulling back",
      "changed expectation",
      "first public touch",
    ],
    stateFields: [
      "intimacy_event",
      "shift_mode",
      "emotional_comfort",
      "sexual_comfort",
      "active_assumption",
      "boundary_state",
      "relationship_effect",
      "immediate_char_response",
      "followup_drivers",
    ],
    promptCompilerSignals: [
      "comfort-increase",
      "awkwardness-avoidance",
      "expectation-possessiveness",
      "uncertainty-jealousy",
      "deeper-trust-fear",
      "changed-boundaries-assumptions",
      "memory-update",
    ],
    memoryRouting: [
      "Update Scenario Book for the live intimacy shift.",
      "Update Memory Book when intimacy becomes a milestone, wound, recurring expectation, altered boundary, aftercare pattern, or callback.",
      "Keep User Book updates limited to explicit user-provided preferences or impersonation-assist material.",
    ],
    continuityLinks: [
      "explicit-memory-core",
      "relationship-tracker",
      "relationship-dynamics",
      "relationship-conflict-tracker",
      "emotional-continuity",
      "emotional-escalation",
      "romantic-sensory-tension",
      "domestic-and-routine-intimacy",
      "quiet-companionship",
      "refusal-and-push",
    ],
    guardrails: [
      "Do not decide how intimacy changes {{user}}.",
      "Do not make intimacy automatically create love, repair trust, erase conflict, or guarantee commitment.",
      "Do not use intimacy to override stated boundaries, withdrawal, distress, meaningful hesitation, or refusal.",
      "Track emotional comfort and sexual comfort separately.",
    ],
  },
];

export function getStoryRuntimeSkill(
  slug: string,
): StoryRuntimeSkill | undefined {
  return storyRuntimeSkills.find((skill) => skill.slug === slug);
}

export function findStoryRuntimeSkillsByTag(
  tag: string,
): StoryRuntimeSkill[] {
  return storyRuntimeSkills.filter((skill) =>
    skill.activationTags.includes(tag),
  );
}

export function findStoryRuntimeSkillsByScope(
  scope: MemoryVaultBookType,
): StoryRuntimeSkill[] {
  return storyRuntimeSkills.filter((skill) => skill.scope.includes(scope));
}
